(()=>{const post=async(path,data)=>{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw new Error(await r.text());return r.json()};
const date=document.querySelector('#date'),lesson=document.querySelector('#lesson'),loc=document.querySelector('#location'),classes=document.querySelector('#classes'),search=document.querySelector('#search'),stateFilter=document.querySelector('#attendance-status'),rows=document.querySelector('#rows'),status=document.querySelector('#status'),all=document.querySelector('#all');let data,restored=false;
date.value=new Date().toLocaleDateString('sv-SE');
const selected=el=>[...el.selectedOptions].map(o=>Number(o.value));
function visible(){if(!data)return[];const cs=new Set(selected(classes)),needle=search.value.trim().toLocaleLowerCase('de');return data.students.filter(x=>{const arrived=Boolean(x.arrival),e=x.currentLocation;if(cs.size&&!cs.has(Number(x.classId)))return false;if(loc.value&&(!e||e.locationCode!==loc.value))return false;if(stateFilter.value==='arrived'&&!arrived)return false;if(stateFilter.value==='absent'&&arrived)return false;if(needle&&!x.studentName.toLocaleLowerCase('de').includes(needle))return false;return true})}
function render(){const list=visible(),arr=list.filter(x=>x.arrival).length;document.querySelector('#total').textContent=list.length;document.querySelector('#arrived').textContent=arr;document.querySelector('#absent').textContent=list.length-arr;rows.replaceChildren();for(const x of list){const e=x.currentLocation,a=x.arrival,tr=document.createElement('tr');tr.className=a?'arrived':'absent';const first=document.createElement('td'),cb=document.createElement('input');cb.type='checkbox';cb.value=x.studentId;cb.className='student';first.append(cb);tr.append(first);const vals=[x.studentName,x.className||'–',a?'Ja':'Nein',e?e.locationName:'–',e?new Date(e.checkedAt).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})+' Uhr':'–',e?.source||'–'];vals.forEach((v,i)=>{const td=document.createElement('td');td.textContent=v;if(i===2)td.className='badge '+(a?'yes':'no');tr.append(td)});rows.append(tr)}if(!list.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=7;td.className='empty';td.textContent='Keine Schüler für diesen Filter.';tr.append(td);rows.append(tr)}all.checked=false;all.indeterminate=false;status.textContent=data?`Stand: ${new Date(data.cutoff).toLocaleString('de-DE')} · ${data.students.length} Schüler geladen`:''}
async function load(){try{data=await post('/attendance-data',{date:date.value,lesson:Number(lesson.value)});if(loc.options.length===1)for(const l of data.locations)loc.add(new Option(`${l.name} (${l.code})`,l.code));const known=new Set([...classes.options].map(o=>Number(o.value)));for(const x of data.students)if(x.classId!=null&&!known.has(Number(x.classId))){classes.add(new Option(x.className,x.classId));known.add(Number(x.classId))}if(!restored){const p=data.preferences||{};if(p.location)loc.value=p.location;for(const o of classes.options)o.selected=(p.classes||[]).map(Number).includes(Number(o.value));restored=true}render()}catch(e){status.textContent='Fehler beim Laden der Anwesenheitsdaten.'}}
document.querySelector('#filters').onsubmit=e=>{e.preventDefault();load()};for(const e of [loc,classes,search,stateFilter])e.oninput=render;document.querySelector('#reset').onclick=()=>{loc.value='';search.value='';stateFilter.value='all';for(const o of classes.options)o.selected=false;render()};all.onchange=()=>document.querySelectorAll('#rows .student').forEach(x=>x.checked=all.checked);document.querySelector('#manual').onclick=async()=>{const ids=[...document.querySelectorAll('#rows .student:checked')].map(x=>Number(x.value));if(!ids.length){status.textContent='Bitte mindestens einen sichtbaren Schüler auswählen.';return}try{await post('/attendance-manual-arrival',{studentIds:ids});await load();status.textContent='Anwesenheit wurde nachvollziehbar bestätigt.'}catch(e){status.textContent='Manuelle Anwesenheit konnte nicht gespeichert werden.'}};document.querySelector('#save').onclick=async()=>{try{await post('/attendance-preferences-save',{location:loc.value||null,classIds:selected(classes)});status.textContent='Arbeitsfilter gespeichert.'}catch(e){status.textContent='Arbeitsfilter konnte nicht gespeichert werden.'}};load();
})();
