package de.igslandstuhl.database.attendance;
import de.igslandstuhl.database.server.Server;import java.sql.*;import java.time.*;import java.util.*;import java.util.function.Supplier;import java.security.SecureRandom;import java.util.Base64;
final class AttendanceRepository {
 static final ZoneId SCHOOL_ZONE=ZoneId.of("Europe/Berlin");private static Supplier<Connection> connections=()->{try{return Server.getInstance().getConnection().getSQLConnection();}catch(Exception e){throw new IllegalStateException(e);}};
 private AttendanceRepository(){} static void useConnections(Supplier<Connection>s){connections=s;}static void initialize(){try{try(Statement s=connection().createStatement()){s.execute("PRAGMA foreign_keys=ON");}}catch(SQLException e){throw new IllegalStateException("Attendance-Datenbank konnte nicht initialisiert werden",e);}}
 static Connection connection()throws SQLException{Connection c=connections.get();try(Statement s=c.createStatement()){s.execute("PRAGMA foreign_keys=ON");}return c;}
 static synchronized String qrSecret()throws SQLException{try(PreparedStatement q=connection().prepareStatement("SELECT value FROM attendance_config WHERE key='qr_secret'");ResultSet r=q.executeQuery()){if(r.next())return r.getString(1);}byte[] b=new byte[32];new SecureRandom().nextBytes(b);String value=Base64.getUrlEncoder().withoutPadding().encodeToString(b);try(PreparedStatement q=connection().prepareStatement("INSERT OR IGNORE INTO attendance_config(key,value) VALUES('qr_secret',?)")){q.setString(1,value);q.executeUpdate();}try(PreparedStatement q=connection().prepareStatement("SELECT value FROM attendance_config WHERE key='qr_secret'");ResultSet r=q.executeQuery()){if(!r.next())throw new SQLException("QR-Secret fehlt");return r.getString(1);}}
 static Map<String,Object> locationByCode(String code)throws SQLException{if(code==null||!code.matches("[A-Za-z0-9_-]{1,32}"))throw new IllegalArgumentException("Standort nicht gefunden");try(PreparedStatement s=connection().prepareStatement("SELECT id,code,name,type,active,display_order FROM attendance_locations WHERE code=? COLLATE NOCASE")){s.setString(1,code);try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalArgumentException("Standort nicht gefunden");return location(r);}}}
 static Map<String,Object> locationById(long id)throws SQLException{try(PreparedStatement s=connection().prepareStatement("SELECT id,code,name,type,active,display_order FROM attendance_locations WHERE id=?")){s.setLong(1,id);try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalArgumentException("Standort nicht gefunden");return location(r);}}}
 static List<Map<String,Object>> locations(boolean activeOnly)throws SQLException{List<Map<String,Object>>x=new ArrayList<>();try(PreparedStatement s=connection().prepareStatement("SELECT id,code,name,type,active,display_order FROM attendance_locations "+(activeOnly?"WHERE active=1 ":"")+"ORDER BY display_order,name" );ResultSet r=s.executeQuery()){while(r.next())x.add(location(r));}return x;}
 private static Map<String,Object> location(ResultSet r)throws SQLException{Map<String,Object>x=new LinkedHashMap<>();x.put("id",r.getLong("id"));x.put("code",r.getString("code"));x.put("name",r.getString("name"));x.put("type",r.getString("type"));x.put("active",r.getBoolean("active"));x.put("displayOrder",r.getInt("display_order"));return x;}
 static synchronized Map<String,Object> qrCheckIn(int studentId,long locationId,Instant now)throws SQLException{return addEvent(studentId,locationId,now,"QR",null);}
 static synchronized Map<String,Object> manualArrival(int studentId,String confirmer,Instant now)throws SQLException{long id=((Number)locations(false).stream().filter(x->"ARRIVAL".equals(x.get("type"))).findFirst().orElseThrow(()->new IllegalStateException("ARRIVAL-Location fehlt")).get("id")).longValue();return addEvent(studentId,id,now,"MANUAL",confirmer);}
 static Map<String,Object> addEvent(int studentId,long locationId,Instant now,String source,String confirmer)throws SQLException{Connection c=connection();boolean ac=c.getAutoCommit();c.setAutoCommit(false);try{Map<String,Object>loc=locationById(locationId);if(!(Boolean)loc.get("active"))throw new IllegalArgumentException("Dieser Standort ist nicht aktiv");String date=LocalDate.ofInstant(now,SCHOOL_ZONE).toString();boolean arrival="ARRIVAL".equals(loc.get("type"));Map<String,Object>existing=arrival?firstArrival(c,studentId,date):lastEvent(c,studentId,date,now);if(existing!=null&&(arrival||Objects.equals(existing.get("locationId"),locationId))){c.rollback();existing.put("status",arrival?"ALREADY_ARRIVED":"ALREADY_THERE");return existing;}try(PreparedStatement s=c.prepareStatement("INSERT INTO attendance_events(student_id,location_id,school_date,checked_at,source,confirmed_by,is_arrival) VALUES(?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){s.setInt(1,studentId);s.setLong(2,locationId);s.setString(3,date);s.setString(4,now.toString());s.setString(5,source);if(confirmer==null)s.setNull(6,Types.VARCHAR);else s.setString(6,confirmer);s.setInt(7,arrival?1:0);s.executeUpdate();try(ResultSet k=s.getGeneratedKeys()){k.next();Map<String,Object>x=new LinkedHashMap<>();x.put("id",k.getLong(1));x.put("studentId",studentId);x.put("locationId",locationId);x.put("locationCode",loc.get("code"));x.put("locationName",loc.get("name"));x.put("locationType",loc.get("type"));x.put("checkedAt",now.toString());x.put("schoolDate",date);x.put("source",source);x.put("confirmedBy",confirmer);x.put("status",arrival?"ARRIVAL_RECORDED":"LOCATION_CHANGED");c.commit();return x;}}
 }catch(SQLException|RuntimeException e){c.rollback();throw e;}finally{c.setAutoCommit(ac);}}
 private static Map<String,Object> firstArrival(Connection c,int sid,String date)throws SQLException{return event(c,"SELECT e.id,e.location_id,l.code,l.name,l.type,e.checked_at,e.source,e.confirmed_by FROM attendance_events e JOIN attendance_locations l ON l.id=e.location_id WHERE e.student_id=? AND e.school_date=? AND e.is_arrival=1 ORDER BY e.checked_at,e.id LIMIT 1",sid,date,null);}
 private static Map<String,Object> lastEvent(Connection c,int sid,String date,Instant cutoff)throws SQLException{return event(c,"SELECT e.id,e.location_id,l.code,l.name,l.type,e.checked_at,e.source,e.confirmed_by FROM attendance_events e JOIN attendance_locations l ON l.id=e.location_id WHERE e.student_id=? AND e.school_date=? AND e.checked_at<=? ORDER BY e.checked_at DESC,e.id DESC LIMIT 1",sid,date,cutoff);}
 private static Map<String,Object> event(Connection c,String sql,int sid,String date,Instant cutoff)throws SQLException{try(PreparedStatement s=c.prepareStatement(sql)){s.setInt(1,sid);s.setString(2,date);if(cutoff!=null)s.setString(3,cutoff.toString());try(ResultSet r=s.executeQuery()){if(!r.next())return null;Map<String,Object>x=new LinkedHashMap<>();x.put("id",r.getLong(1));x.put("locationId",r.getLong(2));x.put("locationCode",r.getString(3));x.put("locationName",r.getString(4));x.put("locationType",r.getString(5));x.put("checkedAt",r.getString(6));x.put("source",r.getString(7));x.put("confirmedBy",r.getString(8));return x;}}}
 static List<Map<String,Object>> snapshot(LocalDate date,Instant cutoff)throws SQLException{List<Map<String,Object>>out=new ArrayList<>();String sql="SELECT s.id,s.first_name,s.last_name,c.id,c.label FROM students s LEFT JOIN classes c ON c.id=s.class ORDER BY c.label,s.last_name,s.first_name";try(PreparedStatement q=connection().prepareStatement(sql);ResultSet r=q.executeQuery()){while(r.next()){Map<String,Object>x=new LinkedHashMap<>();int id=r.getInt(1);x.put("studentId",id);x.put("studentName",r.getString(2)+" "+r.getString(3));x.put("classId",r.getObject(4));x.put("className",r.getString(5));Map<String,Object>a=firstArrival(connection(),id,date.toString()),e=lastEvent(connection(),id,date.toString(),cutoff);x.put("arrival",a);x.put("currentLocation",e);out.add(x);}}return out;}
 static Map<String,Object> upsertLocation(Long id,String code,String name,String type,boolean active,int order)throws SQLException{code=cleanCode(code);name=clean(name,100);if(!Set.of("ARRIVAL","LOCATION").contains(type))throw new IllegalArgumentException("Ungültiger Location-Typ");String sql=id==null?"INSERT INTO attendance_locations(code,name,type,active,display_order) VALUES(?,?,?,?,?)":"UPDATE attendance_locations SET code=?,name=?,type=?,active=?,display_order=? WHERE id=?";try(PreparedStatement s=connection().prepareStatement(sql)){s.setString(1,code);s.setString(2,name);s.setString(3,type);s.setBoolean(4,active);s.setInt(5,order);if(id!=null)s.setLong(6,id);if(s.executeUpdate()!=1)throw new IllegalArgumentException("Standort nicht gefunden");}return locationByCode(code);}
 static void savePreferences(String principal,String location,List<?>classes)throws SQLException{String ids=classes==null?"[]":classes.stream().map(x->String.valueOf(((Number)x).intValue())).toList().toString();try(PreparedStatement s=connection().prepareStatement("INSERT INTO attendance_teacher_preferences(principal,location_code,class_ids,updated_at) VALUES(?,?,?,?) ON CONFLICT(principal) DO UPDATE SET location_code=excluded.location_code,class_ids=excluded.class_ids,updated_at=excluded.updated_at")){s.setString(1,principal);s.setString(2,location);s.setString(3,ids);s.setString(4,Instant.now().toString());s.executeUpdate();}}
 static Map<String,Object> preferences(String p)throws SQLException{try(PreparedStatement s=connection().prepareStatement("SELECT location_code,class_ids FROM attendance_teacher_preferences WHERE principal=?")){s.setString(1,p);try(ResultSet r=s.executeQuery()){if(!r.next())return Map.of("classes",List.of());String raw=r.getString(2).replace("[","").replace("]","").trim();List<Integer>ids=raw.isEmpty()?List.of():Arrays.stream(raw.split(",")).map(String::trim).map(Integer::valueOf).toList();Map<String,Object>x=new LinkedHashMap<>();x.put("location",r.getString(1));x.put("classes",ids);return x;}}}
 private static String cleanCode(String s){s=s==null?"":s.trim().toUpperCase(Locale.ROOT);if(!s.matches("[A-Z0-9_-]{1,32}"))throw new IllegalArgumentException("Code muss 1–32 Zeichen aus A-Z, 0-9, _ oder - enthalten");return s;}private static String clean(String s,int n){s=s==null?"":s.trim();if(s.isEmpty()||s.length()>n)throw new IllegalArgumentException("Ungültiger Name");return s;}
}
