package de.igslandstuhl.database.attendance;
import static org.junit.jupiter.api.Assertions.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.sql.*;import java.time.*;import java.util.*;import org.junit.jupiter.api.*;
class AttendanceRepositoryTest{Connection db;long arrival,la,ws;
 @BeforeEach void setup()throws Exception{db=DriverManager.getConnection("jdbc:sqlite::memory:");try(Statement s=db.createStatement()){s.execute("PRAGMA foreign_keys=ON");s.execute("CREATE TABLE classes(id INTEGER PRIMARY KEY,label TEXT)");s.execute("CREATE TABLE students(id INTEGER PRIMARY KEY,first_name TEXT,last_name TEXT,class INTEGER REFERENCES classes(id))");s.execute("INSERT INTO classes VALUES(5,'5a')");s.execute("INSERT INTO students VALUES(7,'Ada','Lovelace',5)");}for(String n:List.of("attendance_config.sql","attendance_locations.sql","attendance_locations_seed.sql","attendance_events.sql","attendance_events_unique_arrival.sql","attendance_events_student_index.sql","attendance_events_date_index.sql","attendance_events_location_index.sql","attendance_teacher_preferences.sql"))exec(resource("/sql/tables/"+n));AttendanceRepository.useConnections(()->db);AttendanceRepository.initialize();arrival=id("ARRIVAL");la=id("LA");ws=id("WS");}
 @AfterEach void close()throws Exception{db.close();}
 @Test void schemaHasForeignKeysIndexesAndUniqueDailyArrival()throws Exception{try(Statement s=db.createStatement()){assertThrows(SQLException.class,()->s.executeUpdate("INSERT INTO attendance_events(student_id,location_id,school_date,checked_at,source,is_arrival) VALUES(999,"+arrival+",'2026-08-24','2026-08-24T06:00:00Z','QR',1)"));try(ResultSet r=s.executeQuery("PRAGMA foreign_keys")){assertTrue(r.next());assertEquals(1,r.getInt(1));}try(ResultSet r=s.executeQuery("SELECT count(*) FROM sqlite_master WHERE type='index' AND name LIKE 'idx_attendance_events_%'")){assertTrue(r.next());assertEquals(3,r.getInt(1));}}}
 @Test void arrivalIsOnceAndEarlierTimestampIsNeverOverwritten()throws Exception{Instant first=Instant.parse("2026-08-24T05:38:00Z"),later=first.plusSeconds(600);assertEquals("ARRIVAL_RECORDED",AttendanceRepository.qrCheckIn(7,arrival,first).get("status"));Map<String,Object>again=AttendanceRepository.manualArrival(7,"TEACHER:3",later);assertEquals("ALREADY_ARRIVED",again.get("status"));assertEquals(first.toString(),again.get("checkedAt"));assertEquals(1,countEvents());}
 @Test void locationChangesAppendButIdenticalDoubleCheckinDoesNot()throws Exception{Instant t=Instant.parse("2026-08-24T07:01:00Z");AttendanceRepository.qrCheckIn(7,la,t);assertEquals("ALREADY_THERE",AttendanceRepository.qrCheckIn(7,la,t.plusSeconds(5)).get("status"));assertEquals("LOCATION_CHANGED",AttendanceRepository.qrCheckIn(7,ws,t.plusSeconds(60)).get("status"));assertEquals(2,countEvents());}
 @Test void historicalSnapshotUsesLastEventAtCutoff()throws Exception{AttendanceRepository.qrCheckIn(7,arrival,Instant.parse("2026-08-24T05:37:00Z"));AttendanceRepository.qrCheckIn(7,la,Instant.parse("2026-08-24T06:04:00Z"));AttendanceRepository.qrCheckIn(7,ws,Instant.parse("2026-08-24T07:01:00Z"));Map<String,Object>at0850=AttendanceRepository.snapshot(LocalDate.parse("2026-08-24"),Instant.parse("2026-08-24T06:50:00Z")).get(0);assertEquals("LA",((Map<?,?>)at0850.get("currentLocation")).get("locationCode"));Map<String,Object>at0950=AttendanceRepository.snapshot(LocalDate.parse("2026-08-24"),Instant.parse("2026-08-24T07:50:00Z")).get(0);assertEquals("WS",((Map<?,?>)at0950.get("currentLocation")).get("locationCode"));}
 @Test void manualArrivalStoresAuditPrincipalAndDoesNotReplaceQr()throws Exception{Map<String,Object>x=AttendanceRepository.manualArrival(7,"TEACHER:42",Instant.parse("2026-08-24T05:40:00Z"));assertEquals("MANUAL",x.get("source"));assertEquals("TEACHER:42",x.get("confirmedBy"));try(Statement s=db.createStatement();ResultSet r=s.executeQuery("SELECT source,confirmed_by FROM attendance_events")){assertTrue(r.next());assertEquals("MANUAL",r.getString(1));assertEquals("TEACHER:42",r.getString(2));}}
 @Test void secretIsPersistentAndNotPartOfPluginSettings()throws Exception{String a=AttendanceRepository.qrSecret(),b=AttendanceRepository.qrSecret();assertEquals(a,b);assertTrue(a.length()>=43);assertFalse(resource("/meta/paths/post_paths.json").contains("qr_secret"));}
 private long id(String c)throws Exception{try(PreparedStatement s=db.prepareStatement("SELECT id FROM attendance_locations WHERE code=?")){s.setString(1,c);try(ResultSet r=s.executeQuery()){assertTrue(r.next());return r.getLong(1);}}}private int countEvents()throws Exception{try(Statement s=db.createStatement();ResultSet r=s.executeQuery("SELECT count(*) FROM attendance_events")){r.next();return r.getInt(1);}}private void exec(String sql)throws Exception{for(String q:sql.split(";"))if(!q.isBlank())try(Statement s=db.createStatement()){s.execute(q);}}private static String resource(String p)throws Exception{try(InputStream in=AttendanceRepositoryTest.class.getResourceAsStream(p)){assertNotNull(in,p);return new String(in.readAllBytes(),StandardCharsets.UTF_8);}}}
